apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: twitter-bot           # Name of the Kubernetes resource
spec:
  replicas: 2                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: twitter-bot        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: twitter-bot 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: twitter-bot
        image: liamchampton/twitter-bot:0.0.1 
        imagePullPolicy: IfNotPresent